id = "wolfram-language-zed"
name = "Wolfram Language"
version = "0.4.0"
schema_version = 1
description = "Wolfram Language support with LSP"
authors = ["Antonis Aristeidou <tonyaris@outlook.com>"]
themes = ["themes/wolfram-dark.json", "themes/wolfram-light.json", "themes/wolfram-dark-rainbow.json", "themes/wolfram-default.json"]
icon_themes = []
languages = ["languages/wolfram"]
capabilities = []

[grammars.wolfram]
repository = "https://github.com/mtirard/zed-wolfram-treesitter.git"
rev = "e4ebb3fde50391550b2e234bc0333447ca2e48c3"
# [lib]

[language_servers.wolfram-lsp]
name = "Wolfram LSP"
languages = ["Wolfram Language"]

# [context_servers]

# [slash_commands]

# [indexed_docs_providers]
